// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eoavflwnzgvvrtpbvmzy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVvYXZmbHduemd2dnJ0cGJ2bXp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzOTY5NDAsImV4cCI6MjA2OTk3Mjk0MH0.mn3sitofXkPOzAyVQt7n4hVovmYEnb_MtpgNdms-0a8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});